# Generated by Django 4.2.7 on 2024-04-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_post_category_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
