# Generated by Django 4.2.7 on 2024-04-20 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in one of the following formats: '+212123456789', '+2120123456789', or '0123456789'.", regex='^\\+?212?\\d{9}$|^0\\d{9}$')]),
        ),
    ]
