# Generated by Django 4.2.7 on 2024-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0004_alter_post_author'),
        ('core_user', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(related_name='liked_by', to='core_post.post'),
        ),
    ]
